gem 'sinatra'
gem 'sinatra-activerecord'
gem 'pg'
gem 'rake'
gem 'colorize'
gem 'mechanize'
gem 'haml'
gem 'sinatra-flash'
gem 'thin'
gem 'sinatra-contrib'
gem 'sinatra-asset-pipeline'

group :development do
  gem 'rspec'
  gem 'rack-test', require: "rack/test"
  gem 'better_errors', '2.0.0'
  gem "binding_of_caller"
end