gem 'sinatra'
gem 'sinatra-contrib'
gem 'sinatra-activerecord'
gem 'pg'
gem 'rake'
gem 'colorize'
gem 'mechanize'
gem 'haml'
gem 'sinatra-flash'
gem 'thin'

group :development do
  gem 'rspec'
  gem 'rack-test', require: "rack/test"
end
